#
# Makefile for the linux kernel.
#

# Object file lists.

obj-y				:= pdev_bus.o timer.o switch.o pm.o
obj-$(CONFIG_MACH_GOLDFISH)	+= board-goldfish.o
obj-$(CONFIG_MACH_GOLDFISH_ARMV7)	+= board-goldfish.o
